### ISSUE TITLE
Add MsgPack request with feedback

### ISSUE THREAD

**Issue by azawawi** [CurtTilmes/perl6-serializable#3]
Any chance you could add [MsgPack](https://github.com/azawawi/perl6-msgpack/) to your module? Please take a look at it. Your feedback is greatly appreciated.

Have a nice day 👍

**Comment by CurtTilmes** [comment]
I added a Serializer::MsgPack, sorry it took so long to get back to this.

MsgPack looks good.  I see your benchmark dir, but I can't run many of them.  A summary of your results in a doc/benchmark.md or some such would be welcome.  How does it compare with the Perl Data::MessagePack?

Serializable is still just an experimental idea -- Not sure if it is a useful approach or not.
